/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.systembakery.view;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import ec.edu.espe.systembakery.model.Bill;
import ec.edu.espe.systembakery.model.Consumer;
import ec.edu.espe.systembakery.model.Product;
import ec.edu.espe.utils.BsonDownloadDocument;
import ec.edu.espe.utils.Methods;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CodeCrafting Engineers
 */
public class FrmCreateBillConsumer extends javax.swing.JFrame  {

 
    private static MongoDatabase dataB;
    private DefaultTableModel dtmProductList;
    private MongoCollection productCollection;
    private MongoCollection consumerCollection;
    private MongoCollection billCollection;
    private Consumer consumer = new Consumer();
    private ArrayList<Product> products = new ArrayList<>();
    private Bill consumerBill = new Bill();
    
    public FrmCreateBillConsumer(MongoDatabase database) {
        initComponents();
        this.dataB = database;
        createProductTable();
        limitCalendar();
        initializeDatabase(this.dataB);
        setBillId();
    }
    
    private void setBillId(){
        String billId = Methods.getNextBillId(dataB);
        lblBillId.setText(billId);
    }

    private void limitCalendar() {
        Date today = new Date();
        dcDate.setMaxSelectableDate(today);
    }

    public void initializeDatabase(MongoDatabase database) {
        getCollections(database);
        insertInComboBox();
    }

    private void insertInComboBox() {
        Methods.insertItemsComboBox(consumerCollection, "Nombre", cmbConsumerName);
        Methods.insertItemsComboBox(productCollection, "Id", "Nombre", cmbProductId);
    }

    private void getCollections(MongoDatabase database) {
        consumerCollection = BsonDownloadDocument.getCollection(database, "Consumers");
        productCollection = BsonDownloadDocument.getCollection(database, "Products");
        billCollection = BsonDownloadDocument.getCollection(database, "Bills");
    }

    private void createProductTable() {
        dtmProductList = new DefaultTableModel();
        dtmProductList.addColumn("Id");
        dtmProductList.addColumn("Artículo");
        dtmProductList.addColumn("Cantidad");
        dtmProductList.addColumn("Precio U.");
        dtmProductList.addColumn("Valor");
        tblProductList.setModel(dtmProductList);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblBillId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRucCi = new javax.swing.JTextField();
        cmbConsumerName = new javax.swing.JComboBox<>();
        lblErrorConsumer = new javax.swing.JLabel();
        lblErrorCI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcDate = new com.toedter.calendar.JDateChooser();
        lblErrorDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProductAmount = new javax.swing.JTextField();
        cmbProductId = new javax.swing.JComboBox<>();
        btnDiscardBill = new javax.swing.JButton();
        btnDeleteProductInTheList = new javax.swing.JButton();
        lblErrorProductAmount = new javax.swing.JLabel();
        lblErrorProductId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductList = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnEnterToOrderList = new javax.swing.JButton();
        btnPrintBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(780, 372));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Panadería: El Trigo de Oro");

        jLabel2.setText("RTN: 00121-00");

        jLabel11.setText("FACTURA:");

        lblBillId.setText("No. 000-000-000000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBillId)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(lblBillId)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setText("Cliente:");

        jLabel5.setText("RUC / CI:");

        txtRucCi.setEditable(false);
        txtRucCi.setBackground(new java.awt.Color(204, 204, 204));

        cmbConsumerName.setBackground(new java.awt.Color(204, 204, 204));
        cmbConsumerName.setEditable(true);
        cmbConsumerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cmbConsumerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsumerNameActionPerformed(evt);
            }
        });

        lblErrorConsumer.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorCI.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Fecha de Emisión:");

        dcDate.setDateFormatString("dd/MM/yyyy");
        dcDate.setMaxSelectableDate(new java.util.Date(253370786512000L));

        lblErrorDate.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorConsumer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtRucCi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblErrorCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblErrorDate, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorConsumer, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                            .addComponent(lblErrorCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(txtRucCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setText("Id:");

        jLabel8.setText("Cantidad:");

        txtProductAmount.setBackground(new java.awt.Color(204, 204, 204));

        cmbProductId.setBackground(new java.awt.Color(204, 204, 204));
        cmbProductId.setEditable(true);
        cmbProductId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnDiscardBill.setBackground(new java.awt.Color(255, 204, 153));
        btnDiscardBill.setText("Descartar Factura");
        btnDiscardBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardBillActionPerformed(evt);
            }
        });

        btnDeleteProductInTheList.setBackground(new java.awt.Color(255, 204, 153));
        btnDeleteProductInTheList.setText("Borrar Producto Seleccionado");
        btnDeleteProductInTheList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductInTheListActionPerformed(evt);
            }
        });

        lblErrorProductAmount.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorProductId.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorProductAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProductAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDeleteProductInTheList))
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(lblErrorProductId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDiscardBill, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErrorProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorProductAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProductAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiscardBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteProductInTheList)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tblProductList.setBackground(new java.awt.Color(255, 204, 102));
        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Artículo", "Cantidad", "Precio U.", "Precio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductList);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        btnEnterToOrderList.setBackground(new java.awt.Color(255, 204, 153));
        btnEnterToOrderList.setText("Ingresar a la Lista de Compras");
        btnEnterToOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterToOrderListActionPerformed(evt);
            }
        });

        btnPrintBill.setBackground(new java.awt.Color(255, 204, 153));
        btnPrintBill.setText("Imprimir");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnEnterToOrderList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(btnPrintBill)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterToOrderList)
                    .addComponent(btnPrintBill))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterToOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterToOrderListActionPerformed
        if (checkFieldAttributes()) {
            String firstPartCmbProductId = getProductId();
            Methods.addElemenToTable(productCollection, firstPartCmbProductId, txtProductAmount, dtmProductList);
        }
    }//GEN-LAST:event_btnEnterToOrderListActionPerformed

    private boolean checkFieldAttributes() throws HeadlessException {
        if (!checkConsumer()) {
            lblErrorConsumer.setText("Elija un cliente de la lista");
            cmbConsumerName.requestFocus();
            return false;
        } else {
            lblErrorConsumer.setText("");
        }
        if (!checkRucCi()) {
            lblErrorCI.setText("Escriba correctamente el C.I.");
            txtRucCi.requestFocus();
            return false;
        } else {
            lblErrorCI.setText("");
        }
        if (!checkDate()) {
            lblErrorDate.setText("Use el calendario");
            dcDate.requestFocus();
            return false;
        } else {
            lblErrorDate.setText("");
        }

        if (!checkProductId()) {
            lblErrorProductId.setText("Elija una opción no vacía de la lista");
            cmbProductId.requestFocus();
            return false;
        } else {
            lblErrorProductId.setText("");
        }
        if (!checkProductAmount()) {
            lblErrorProductAmount.setText("Debe ser menos de 99 objetos");
            txtProductAmount.requestFocus();
            return false;
        } else {
            lblErrorProductAmount.setText("");
        }
        return true;
    }

    private String getProductId() {
        return cmbProductId.getSelectedItem().toString().split(" --> ")[0];
    }

    private boolean checkProductAmount() {
        return txtProductAmount.getText().matches("^\\d{1,2}$");
    }

    private boolean checkDate() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            return dateFormat.format(dcDate.getDate()).matches("^(0[1-9]|[1-2][0-9]|3[0-1])/(0[1-9]|1[0-2])/\\d{4}$");
        } catch (Exception e) {
            return false;
        }
    }

    private boolean checkProductId() {
        String firstPartCmbProductId = getProductId();
        return firstPartCmbProductId.matches("^[A-Z]\\d{3}$");
    }

    private boolean checkRucCi() {
        return txtRucCi.getText().matches("^\\d{10}$");
    }

    private boolean checkConsumer() {
        return cmbConsumerName.getSelectedItem().toString().matches("^[A-Z][a-z]+ [A-Z][a-z]+$");
    }
    
    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        try {
            if (checkFieldAttributes()) {
                consumer = Methods.getConsumer(cmbConsumerName.getSelectedItem().toString(), consumerCollection);
                Date date = dcDate.getDate();

                FrmBill bill = new FrmBill(consumer, dtmProductList, consumerBill, date);

                PrinterJob printerJob = PrinterJob.getPrinterJob();
                printerJob.setPrintable(bill);
                boolean top = printerJob.printDialog();
                if (top) {
                    printerJob.print();
                }

                cleanFields();
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Error de Impresión", "Error: \n" + e, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void cleanFields() {
        txtProductAmount.setText("");
        txtRucCi.setText("");
        cmbConsumerName.setSelectedIndex(0);
        cmbProductId.setSelectedIndex(0);
        dtmProductList.getDataVector().removeAllElements();
        tblProductList.updateUI();
        dcDate.setDate(null);
        
        products.clear();
    }
    
    private void btnDeleteProductInTheListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductInTheListActionPerformed
        if(tblProductList.getSelectedRow() != -1){
            int row = tblProductList.getSelectedRow();
            products.remove(row);
            dtmProductList.removeRow(row);
        }
    }//GEN-LAST:event_btnDeleteProductInTheListActionPerformed

    private void btnDiscardBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardBillActionPerformed
       boolean option = JOptionPane.showConfirmDialog(null, "Realmente desea borrar TODA la factura", "Borrar Factura",
                JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION;
        if(option){
            cleanFields();
        }
    }//GEN-LAST:event_btnDiscardBillActionPerformed

    private void cmbConsumerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsumerNameActionPerformed
        String consumerSelected = (String) cmbConsumerName.getSelectedItem();
        boolean verifString = consumerSelected.equals("");
        
        if(verifString){
            txtRucCi.setText("");
        }else{
            consumer = Methods.getConsumer(consumerSelected, consumerCollection);
            txtRucCi.setText(consumer.getcI());
        }
    }//GEN-LAST:event_cmbConsumerNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateBillConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateBillConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateBillConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateBillConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreateBillConsumer(dataB).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProductInTheList;
    private javax.swing.JButton btnDiscardBill;
    private javax.swing.JButton btnEnterToOrderList;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JComboBox<String> cmbConsumerName;
    private javax.swing.JComboBox<String> cmbProductId;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBillId;
    private javax.swing.JLabel lblErrorCI;
    private javax.swing.JLabel lblErrorConsumer;
    private javax.swing.JLabel lblErrorDate;
    private javax.swing.JLabel lblErrorProductAmount;
    private javax.swing.JLabel lblErrorProductId;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTextField txtProductAmount;
    private javax.swing.JTextField txtRucCi;
    // End of variables declaration//GEN-END:variables

}
