package ec.edu.espe.systembakery;

import java.awt.Color;

/**
 *
 * @author CodeCrafting Engineers
 */
public class FrmBillMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmCreateBill
     */
    public FrmBillMenu() {
        initComponents();
        this.getGraphics().setColor(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogoBillMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmReturnToPrincipalMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmMakePurchaseOrderToSupplier = new javax.swing.JMenuItem();
        itmMakeBillToConsumer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        itmCheckPurchaseOrders = new javax.swing.JMenuItem();
        itmCheckBills = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú Órdenes de Compra");

        lblLogoBillMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenes/LogoBillMenu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogoBillMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblLogoBillMenu)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");

        itmReturnToPrincipalMenu.setText("Regresar al Menú Principal");
        itmReturnToPrincipalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReturnToPrincipalMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itmReturnToPrincipalMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        itmMakePurchaseOrderToSupplier.setText("Realizar Orden de Compra a Proveedor");
        itmMakePurchaseOrderToSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMakePurchaseOrderToSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(itmMakePurchaseOrderToSupplier);

        itmMakeBillToConsumer.setText("Realizar Factura a Consumidor");
        itmMakeBillToConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMakeBillToConsumerActionPerformed(evt);
            }
        });
        jMenu2.add(itmMakeBillToConsumer);
        jMenu2.add(jSeparator1);

        jMenu3.setText("Consultar");

        itmCheckPurchaseOrders.setText("Orden de Compras");
        jMenu3.add(itmCheckPurchaseOrders);

        itmCheckBills.setText("Facturas");
        jMenu3.add(itmCheckBills);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmReturnToPrincipalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReturnToPrincipalMenuActionPerformed
        if (true) { //read users from and compare user name and password
            FrmBakery frmBakery = new FrmBakery();
            this.setVisible(false);
            frmBakery.setVisible(true);
        }
    }//GEN-LAST:event_itmReturnToPrincipalMenuActionPerformed

    private void itmMakeBillToConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMakeBillToConsumerActionPerformed
        FrmCreateBillConsumer frmCreateBillConsumer = new FrmCreateBillConsumer();
        this.setVisible(false);
        frmCreateBillConsumer.setVisible(true);
    }//GEN-LAST:event_itmMakeBillToConsumerActionPerformed

    private void itmMakePurchaseOrderToSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMakePurchaseOrderToSupplierActionPerformed
        FrmCreatePurchaseOrder frmCreatePurchaseOrder = new FrmCreatePurchaseOrder();
        this.setVisible(false);
        frmCreatePurchaseOrder.setVisible(true);
    }//GEN-LAST:event_itmMakePurchaseOrderToSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBillMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBillMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBillMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBillMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBillMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCheckBills;
    private javax.swing.JMenuItem itmCheckPurchaseOrders;
    private javax.swing.JMenuItem itmMakeBillToConsumer;
    private javax.swing.JMenuItem itmMakePurchaseOrderToSupplier;
    private javax.swing.JMenuItem itmReturnToPrincipalMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblLogoBillMenu;
    // End of variables declaration//GEN-END:variables
}
